version: '1'

services:
  booksapiapp:
    image: booksapi
    container_name: booksapiapp
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - mybridgenetwork
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - mybridgenetwork
    volumes:
      - mymongovolume:/data/db
      - mymongovolume:/data/configdb
    restart: always

  

networks:
  mybridgenetwork:
    driver: bridge

volumes:
  mymongovolume: